Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2024-08, with the labels that each got.

#48 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, size/s

#43 Proper versioning update mechanism including expiration of versions
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
  pkg/controller/maintenance/reconciler.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#52 Set hostname env variable for node as hostname in events
  charts/internal/falco/templates/falco-pod-template.tpl
Labels: needs/ok-to-test, needs/review, size/xs
