Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2024-12, with the labels that each got.

#115 Set Falo version 0.39.2 as supported
  falco/falco-profile.yaml
  falco/falcoversions.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#119 Update base image to debian 12
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#117 Remove deprecated configuration options
  charts/internal/falco/templates/falco-pod-template.tpl
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#123 Add new falcosidekick and falcoctl versions
  falco/falco-profile.yaml
  falco/falcoctlversions.yaml
  falco/falcosidekickversions.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s
