Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2024-11, with the labels that each got.

#88 Enable dependabot
  .github/dependabot.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#89 Update Gardener to version 1.106.0
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/profile/v1alpha1/zz_generated.conversion.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#94 Fix configmap spec in documentation
  docs/FalcoExtension.md
Labels: needs/review

#95 Add verify to release steps
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#101 [fix] Fixing deadlock between maintenance and validation controllers
  go.mod
  go.sum
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/controller/maintenance/add.go
  pkg/controller/maintenance/reconciler.go
Labels: needs/ok-to-test, needs/review, size/m

#103 Add missing permissions for shoot update during maintenance
  charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
  pkg/controller/maintenance/reconciler.go
Labels: needs/ok-to-test, needs/review, size/xs

#105 Fix delete loop of death
  pkg/controller/lifecycle/actuator.go
Labels: needs/ok-to-test, needs/review, size/xs

#106 Fix pipleline
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#113 Add new Falco version and remove expired versions
  falco/falco-profile.yaml
  falco/falcoversions.yaml
  imagevector/images.yaml
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/controller/maintenance/reconciler.go
  pkg/profile/profile.go
  pkg/profile/profile_test.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: needs/ok-to-test, needs/review, size/m
