Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2024-10, with the labels that each got.

#64 Add preview flag to admission controller
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-falco-service/values.yaml
  pkg/admission/validator/shoot_validator.go
Labels: needs/ok-to-test, needs/review, size/xs

#65 Fix priority classes for extension controller and shoot
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
Labels: needs/review

#66 Fix priority class names for admission controller
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
  charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
Labels: needs/review, size/xs

#67 Fix priority class configuration
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
  charts/gardener-extension-admission-shoot-falco-service/values.yaml
  charts/gardener-extension-shoot-falco-service/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#68 Add priority class config for Falcosidekick
  charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
  charts/internal/falco/values.yaml
  pkg/values/falcovalues.go
Labels: reviewed/ok-to-test, needs/review, size/xs

#69 Avoid deployment failure
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#71 Fixed typo in env variable
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#72 Add logging for restricted usage
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
Labels: needs/ok-to-test, needs/review, size/xs

#70 Only restrict extension usage if not previously enabled
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
Labels: needs/ok-to-test, needs/rebase, needs/review, size/s

#73 Remove unused code
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
Labels: needs/ok-to-test, needs/review, size/s

#76 Fixed expiration date nil pointer for falco related versions
  hack/api-reference/config.md
  pkg/apis/profile/v1alpha1/types.go
  pkg/profile/profile.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/s

#79 Fix and add shoot validator tests
  pkg/admission/validator/shoot_validator_test.go
Labels: needs/ok-to-test, needs/review, size/s

#78 Removing the metadata_download configuration
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#80 Support new falco version with new ruleset
  falco/falco-profile.yaml
  falco/falcoversions.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#81 Make /metrics endpoint available via http
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#82 Deploy Falco ScrapeConfig into seed control plane namespace
  charts/internal/extension-shoot-falco-service-chart-seed/Chart.yaml
  charts/internal/extension-shoot-falco-service-chart-seed/templates/scrapeconfig.yam
  charts/internal/extension-shoot-falco-service-chart-seed/values.yaml
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
Labels: needs/ok-to-test, needs/review, size/m

#83 Add new versions, remove old ones
  falco/falco-profile.yaml
  falco/falcoctlversions.yaml
  falco/falcosidekickversions.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s
