Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2024-06, with the labels that each got.

#20 Update to golang 1.22.3
  Dockerfile
  go.mod
Labels: needs/ok-to-test, needs/review, size/xs

#16 Validator and mutator webhooks
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
  go.mod
  go.sum
  pkg/admission/cmd/options.go
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
  pkg/admission/mutator/webhook.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/bla
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/v1alpha1/zz_generated.conversion.go
  pkg/apis/service/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/service/validation/validation.go
  pkg/apis/service/zz_generated.deepcopy.go
  pkg/falcovalues/falcovalues.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#23 Fix extension deletion and upgrade to Gardener v1.96.1
  go.mod
  go.sum
  pkg/controller/lifecycle/actuator.go
Labels: needs/ok-to-test, needs/review, size/m

#24 tidy up
  hack/cherry-pick-pull.sh
Labels: needs/ok-to-test, needs/review, size/xs

#26 Update of go modules
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/s

#27 Cert updates
  README.md
  imagevector/images.yaml
  imagevector/imagevector.go
  imagevector/imagevector_test.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/falcovalues/falcovalues.go
  pkg/secrets/certs.go
  pkg/secrets/certs_test.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#29 General cleanup
  Makefile
  charts/internal/falco/templates/falco-pod-template.tpl
  charts/internal/falco/values.yaml
  cmd/gardener-extension-shoot-falco-service/app/app.go
  falco/falcoversions.yaml
  pkg/falcovalues/falcovalues.go
Labels: needs/ok-to-test, needs/review, size/s

#30 Cleanup & more tests
  falco/falcoversions.yaml
  imagevector/images.yaml
  imagevector/imagevector_test.go
  pkg/falcovalues/falcovalues.go
  pkg/falcovalues/falcovalues_test.go
  pkg/secrets/certs.go
  pkg/secrets/tokenissuer.go
Labels: needs/ok-to-test, needs/review, size/m

#31 Fix imagevector
  docs/FalcoExtension.md
  imagevector/imagevector.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#32 Fix typo in values.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/application/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs
