Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-02, with the labels that each got.

#155 Fix token lifetime
  pkg/controller/lifecycle/actuator.go
  pkg/secrets/tokenissuer.go
  pkg/secrets/tokenissuer_test.go
  pkg/values/falcovalues_test.go
Labels: needs/ok-to-test, needs/review, size/s

#159 Bump golang-1.23.6 ci image
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#158 Update apis/profile and improve profile manager
  cmd/gardener-extension-shoot-falco-service/app/app.go
  hack/api-reference/config.md
  pkg/apis/profile/doc.go
  pkg/apis/profile/install/install.go
  pkg/apis/profile/register.go
  pkg/apis/profile/types.go
  pkg/apis/profile/v1alpha1/doc.go
  pkg/apis/profile/v1alpha1/register.go
  pkg/apis/profile/v1alpha1/types.go
  pkg/apis/profile/zz_generated.deepcopy.go
  pkg/controller/lifecycle/actuator.go
  pkg/profile/profile.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/m

#160 Bump golang-1.23.6
  Dockerfile
  go.mod
Labels: needs/ok-to-test, needs/review, size/xs

#131 Vali logging via falcosidekick
  charts/internal/extension-shoot-falco-service-chart-seed/templates/falcosidekick-sa.yaml
  charts/internal/falco/templates/falcosidekick-deployment.yaml
  charts/internal/falco/templates/falcosidekick-logging-rbac.yaml
  charts/internal/falco/templates/falcosidekick-rbac.yaml
  charts/internal/falco/values.yaml
  falco/falco-profile.yaml
  falco/falcosidekickversions.yaml
  imagevector/images.yaml
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  pkg/utils/vali.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#162 Update all dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#161 Fix glitch in shoot mutator
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
Labels: needs/ok-to-test, needs/review, size/s

#151 Prepare for deployment of admission controller by gardener-operator
  .ci/pipeline_definitions
  charts/gardener-extension-admission-shoot-falco-service/Chart.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/application/.helmignore
  charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/application/values.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/.helmignore
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/secret-kubconfig.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
  charts/gardener-extension-admission-shoot-falco-service/templates/_helpers.tpl
  charts/gardener-extension-admission-shoot-falco-service/values.yaml
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#165 Added new falcosidekick version 2.31.1
  falco/falco-profile.yaml
  falco/falcosidekickversions.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#166 Publish falco profile as oci artefact
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#167 fix build issue
  .ci/pipeline_definitions
Labels: needs/review

#168 Unified logging for maintenance
  go.mod
  go.sum
  pkg/controller/maintenance/add.go
  pkg/controller/maintenance/reconciler.go
Labels: needs/ok-to-test, needs/review, size/s

#169 attach falco rules to com component
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#174 fix pipeline 6
  .ci/pipeline_definitions
Labels: needs/review

#176 Add falco rule exception for new runc version
  falco/rules/3.2.0/falco_rules.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#177 Add rule checksums to Falco daemonset
  charts/internal/falco/templates/falco-pod-template.tpl
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, size/s

#179 Add compression capability for Falco custom rules
  go.mod
  pkg/constants/constants.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/l

#182 Do not use component-cli for image-vector processing
  .ci/component_descriptor
  .ci/hack/component_descriptor
Labels: reviewed/ok-to-test, needs/review, size/m

#183 fix: Use relative path working on Concourse
  .ci/component_descriptor
Labels: needs/review

#184 fix: Properly write ocm to expected output
  .ci/component_descriptor
Labels: needs/review, size/xs

#189 Improve custom rule handling
  Makefile
  hack/validate-falco-rules
  hack/validate-imagevector.py
  pkg/constants/constants.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#190 Add Dynatrace exception
  falco/rules/3.2.0/falco_rules.yaml
Labels: needs/ok-to-test, needs/review, size/xs
