Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-08, with the labels that each got.

#319 Respect gardener critical component taint
  charts/internal/falco/values.yaml
  pkg/values/falcovalues.go
Labels: needs/review, size/xs

#323 Update docs
  docs/extension-configuration.md
  docs/falco-configuration.md
  docs/falco-profile.md
Labels: needs/review, size/m

#325 Decrease memory requests and limits
  charts/internal/falco/values.yaml
Labels: needs/review, size/xs

#327 Add build badge
  README.md
Labels: area/delivery, kind/cleanup, needs/review, size/xs

#337 Fix volume mounts for container engine in 0.40.0
  charts/internal/falco/templates/0helpers.tpl
Labels: needs/review, size/xs

#339 Add generation for `Extension` example
  Makefile
  example/.gitignore
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, needs/review, size/s
