Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-01, with the labels that each got.

#133 Minor cleanup
  charts/internal/falco/templates/falco-pod-template.tpl
  charts/internal/falco/templates/falcosidekick-deployment.yaml
  pkg/values/falcovalues.go
Labels: needs/ok-to-test, needs/review, size/xs

#134 Add option to deploy falco-falcosidekick networkpolicy
  charts/internal/falco/templates/falcosidekick-networkpolicy.yaml
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#137 New config
  charts/internal/falco/templates/falcosidekick-certs-secret.yaml
  charts/internal/falco/templates/falcosidekick-deployment.yaml
  charts/internal/falco/templates/falcosidekick-networkpolicy.yaml
  charts/internal/falco/templates/falcosidekick-rbac.yaml
  charts/internal/falco/templates/falcosidekick-secrets.yaml
  charts/internal/falco/templates/falcosidekick-service.yaml
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
  hack/LICENSE_BOILERPLATE.txt
  hack/api-reference/service.md
  hack/update-codegen.sh
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_suite_test.go
  pkg/admission/mutator/shoot_mutator_test.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_suite_test.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/profile/v1alpha1/zz_generated.conversion.go
  pkg/apis/profile/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/profile/v1alpha1/zz_generated.defaults.go
  pkg/apis/profile/zz_generated.deepcopy.go
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/v1alpha1/zz_generated.conversion.go
  pkg/apis/service/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/service/v1alpha1/zz_generated.defaults.go
  pkg/apis/service/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/migration/migrator.go
  pkg/profile/profile.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#147 Add new Falco versions (deprecate old ones)
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
  falco/falco-profile.yaml
  falco/falcoctlversions.yaml
  falco/falcoversions.yaml
  imagevector/images.yaml
  pkg/admission/validator/shoot_validator.go
  pkg/profile/profile.go
Labels: needs/ok-to-test, needs/review, size/m

#148 mitigate gardener api change
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/config.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/xs

#150 Add `ok-to-test` label for dependabot
  .github/dependabot.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#154 fix falcoctlversion (again)
  falco/falco-profile.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs
