Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-03, with the labels that each got.

#193 Remove env config
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-shoot-falco-service/templates/deployment.yaml
  charts/internal/falco/templates/falcosidekick-deployment.yaml
  charts/internal/falco/templates/falcosidekick-secrets.yaml
  charts/internal/falco/templates/falcosidekick-service.yaml
  charts/internal/falco/values.yaml
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
Labels: needs/ok-to-test, needs/review, size/m

#195 Finalize configuration options for restricted usage
  Makefile
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/values.yaml
  pkg/admission/validator/shoot_validator.go
  pkg/constants/constants.go
Labels: needs/ok-to-test

#201 Update verify image golang 1.24.1
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#204 Update x/net 0.36.0
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/xs

#205 Remove last reference of architecture for images
  crds/crd-falco-profile.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#207 Drop support for Shoots with Kubernetes version <= 1.26
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/service.yaml
  hack/api-reference/config.json
  hack/api-reference/config.md
  hack/api-reference/service.json
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#212 mark Falco 0.40.0 as supported
  falco/falco-profile.yaml
  falco/falcoversions.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#213 Update gardener to 1.114.1
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review

#216 Add integration tests
  .test-defs/TestFalco.yaml
  Makefile
  test/integration/.gitignore
  test/integration/README.md
  test/integration/conftest.py
  test/integration/falco-integration.sh
  test/integration/falcotest/__init__.py
  test/integration/falcotest/falcolib.py
  test/integration/requirements.txt
  test/integration/test_falco.py
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#217 Adopt upstream exception for new runc version
  falco/rules/3.2.0/falco_rules.yaml
Labels: needs/ok-to-test, needs/review, size/xs
