Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-07, with the labels that each got.

#301 Remove CPU limits for Falco pod
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#303 migrate CICD-Pipeline to GitHub-Actions
  .ci/pipeline_definitions
  .ci/set_dependency_version
  .github/actions/prepare-release/action.yaml
  .github/actions/prepare-release/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .ocm/base-component.yaml
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#302 Fix Falcosidekick image in all output config cases
  pkg/values/falcovalues.go
Labels: needs/ok-to-test, needs/review, size/s

#310 Add new readme
  README.md
Labels: needs/review, size/s

#318 Increase memory requests and limits to deal with leaking Falco
  charts/internal/falco/values.yaml
Labels: needs/review, size/xs
