Repository gardener/gardener-extension-shoot-falco-service, pull requests merged in 2025-04, with the labels that each got.

#218 Extension definition API change
  Makefile
  charts/internal/falco/templates/falcosidekick-deployment.yaml
  charts/internal/falco/templates/falcosidekick-logging-rbac.yaml
  charts/internal/falco/values.yaml
  docs/FalcoExtension.md
  hack/api-reference/service.md
  hack/test.sh
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/apis/config/types.go
  pkg/apis/profile/v1alpha1/register.go
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/v1alpha1/zz_generated.conversion.go
  pkg/apis/service/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/service/validation/validation.go
  pkg/apis/service/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/migration/issue215migration.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  pkg/values/falcovalues.go
  pkg/values/falcovalues_test.go
  test/integration/falcotest/falcolib.py
  test/integration/test_falco.py
Labels: kind/api-change, needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/xl

#142 Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31
  charts/gardener-extension-admission-shoot-falco-service/charts/runtime/templates/service.yaml
Labels: area/high-availability, area/networking, reviewed/lgtm, needs/ok-to-test, size/xs

#222 Fix for broken vali logging
  hack/api-reference/service.md
  pkg/values/falcovalues.go
Labels: needs/ok-to-test, needs/review, size/xs

#223 Change maxUnavailable to 20%
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#226 Restrict usage via namespace annotation
  cmd/gardener-extension-admission-shoot-falco-service/app/app.go
  hack/api-reference/service.md
  pkg/admission/validator/namespace.go
  pkg/admission/validator/project.go
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
  pkg/constants/constants.go
Labels: reviewed/lgtm, needs/ok-to-test, size/l

#230 Fix central logging validation
  hack/api-reference/service.md
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/shoot_validator_test.go
Labels: needs/ok-to-test, needs/review, size/s

#233 Update verify image golang 1.24.2
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#238 Fix empty extension spec
  pkg/admission/mutator/shoot_mutator.go
  pkg/admission/mutator/shoot_mutator_test.go
Labels: needs/ok-to-test, needs/review, size/xs, status/closed

#247 Improve error message of admission controller
  pkg/admission/validator/shoot_validator.go
Labels: needs/ok-to-test, needs/review, size/xs

#234 Fix Falco extension configuration
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/values/falcovalues.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/s

#244 Update transitive dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#251 Remove Falcoctl entries from profile
  Makefile
  falco/falco-profile.yaml
  falco/falcoctlversions.yaml
  hack/generate-falco-profile
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#250 Enable Falco metrics endpoint
  charts/internal/falco/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#253 Remove obsolete falco and falcosidekick versions
  falco/falco-profile.yaml
  falco/falcosidekickversions.yaml
  falco/falcoversions.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#245 Revisit roles for seed and shoot resources
  charts/internal/extension-shoot-falco-service-chart-seed/templates/falcosidekick-token-request-secret.yaml
  charts/internal/falco/templates/clusterrole.yaml
  charts/internal/falco/templates/clusterrolebinding.yaml
  charts/internal/falco/templates/falco-pod-template.tpl
  charts/internal/falco/templates/serviceaccount.yaml
  charts/internal/falco/values.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#252 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-falco-service/templates/rbac.yaml
Labels: area/quality, kind/regression, needs/ok-to-test, needs/review, size/xs

#257 remove test log file
  test/integration/test.log
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#259 Dont commit intgeration test log file
  test/integration/.gitignore
Labels: needs/ok-to-test, needs/review, size/xs

#263 Remove unused project access from admission controller
  charts/gardener-extension-admission-shoot-falco-service/charts/application/templates/rbac.yaml
Labels: needs/ok-to-test, needs/review, size/xs
